name: CI

# ✅ ให้ workflow เข้าถึงเนื้อหา repo ได้
permissions:
  contents: read

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    name: Frontend (Vite/React)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: K-Merge-Frontend-Dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # ✅ ดึงทั้ง repo (แก้ exit code 128)
          persist-credentials: true # ✅ ให้ token ใช้ได้

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npx tsc -b --pretty false

      - name: Build
        run: npm run build

  backend:
    name: Backend (NestJS)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kmerge_api2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint (no autofix)
        run: npx eslint "{src,apps,libs,test}/**/*.ts"

      - name: Build
        run: npm run build

      - name: Test (unit)
        run: npm test -- --ci
